os: linux
dist: jammy
language: minimal

notifications:
  email:
    on_success: change
    on_failure: always

jobs:
  include:
  - stage: test
    name: "conda linux"
    os: linux
    dist: jammy
    env: TEST_PROFILE="proteus-conda"
    install:
      - git lfs pull
      - sudo apt-get update
      - wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge3.sh;
      - bash miniforge3.sh -b -p $HOME/miniforge3
      - source "$HOME/miniforge3/etc/profile.d/conda.sh"
      - hash -r
      - mamba config --set always_yes yes --set changeps1 no
      - mamba update -q mamba
      - mamba info -a
      - mamba env create -f environment-dev.yml
      - mamba activate proteus-dev
      - PROTEUS_OPT="-g0 -O1" pip install -v . --no-build-isolation --no-binary=:all:
    script:
      - export MPLBACKEND="AGG"
      - py.test -v --forked --import-mode=importlib test --ignore test/MeshAdaptPUMI --ignore test/test_mbd_chrono.py --ignore test/AddedMass
